# This file is used to configure Travis CI for a project.
# It specifies the programming language, environment, and commands to run during the build process.

sudo: required

services:
  - docker

before_install:
  - docker build -t sandeep199522/docker-react -f Dockerfile.dev .

script:
  - docker run sandeep199522/docker-react npm run test -- --coverage
