# This file is used to configure Travis CI for a project.

language: node_js
node_js:
  - "16" # Adjust to your Node.js version

services:
  - docker

before_install:
  - docker --version
  - docker build -t sandeep199522/docker-react -f Dockerfile.dev .
  - docker images

script:
  - docker run sandeep199522/docker-react npm run test -- --coverage
